#!/usr/bin/env sh

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
ITEM_DIR="$HOME/.config/sketchybar/items"

# run helper program
# TODO: UNCOMMENT WHEN DYNAMIC ISLAND HAS BEEN FIXED
# ISLANDHELPER=git.crissnb.islandhelper
# killall islandhelper
# $HOME/.config/sketchybar/plugins/Dynamic-Island-Sketchybar/helper/islandhelper $ISLANDHELPER &


source $HOME/.config/sketchybar/colors.sh
source $HOME/.config/sketchybar/icons.sh
# TODO: UNCOMMENT WHEN DYNAMIC ISLAND HAS BEEN FIXED
# source "$PLUGIN_DIR/Dynamic-Island-Sketchybar/config.sh"

export FONT="IBM Plex Mono"
export NERD_FONT="JetBrainsMono Nerd Font"

sketchybar --bar height=30        \
                 blur_radius=100  \
                 position=top     \
                 padding_left=10  \
                 padding_right=10 \
                 color=0x15000000 \
                 shadow=on

sketchybar --default updates=when_shown                       \
                     drawing=on                               \
                     icon.font="$NERD_FONT:Regular:14.0"      \
                     icon.color=0xffffffff                    \
                     label.font="$FONT:Medium:14.0"            \
                     label.color=0xffffffff                   \
                     label.padding_left=4                     \
                     label.padding_right=4                    \
                     icon.padding_left=4                      \
                     icon.padding_right=4

source $ITEM_DIR/apple.sh
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/window_title.sh
source $ITEM_DIR/clock.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/wifi.sh
# TODO: UNCOMMENT WHEN DYNAMIC ISLAND HAS BEEN FIXED
# source "$PLUGIN_DIR/Dynamic-Island-Sketchybar/item.sh"

sketchybar --update

echo "sketchybar configuration loaded.."
