-- local utils = require("utils")
-- local colors = require('github-theme.colors')
--
-- local fg_bg = utils.fg_bg
-- local bg = utils.bg
--
-- local black = colors.black
-- local black2 = colors.black2
-- local green = colors.green
-- local red = colors.red
-- local white = colors.white
--
-- fg_bg("TelescopeBorder", darker_black, darker_black)
-- fg_bg("TelescopePromptBorder", black2, black2)
--
-- fg_bg("TelescopePromptNormal", white, black2)
-- fg_bg("TelescopePromptPrefix", red, black2)
--
-- bg("TelescopeNormal", darker_black)
--
-- fg_bg("TelescopePreviewTitle", black, green)
-- fg_bg("TelescopePromptTitle", black, red)
-- fg_bg("TelescopeResultsTitle", darker_black, darker_black)
--
-- bg("TelescopeSelection", black2)
--
